In [1]:
import pandas as pd
import numpy as np
np.random.seed(0)
import pulp

import sys
sys.path.insert(0, '../..')
import assignment
import bottleneck_assignment
import leximin_assignment

import warnings

In [2]:
e = 1e-2

cost_matrix = np.array([
    [0, 1 - 2 * e, 1 - e, 1],
    [0, 1 - 2 * e, 1, 1],
    [0, 0, 1 - 2 * e, 1],
    [0, 0, 0, 1 - e]
])
capacities = [1, 1, 1, 1]

cost_matrix

array([[0.  , 0.98, 0.99, 1.  ],
       [0.  , 0.98, 1.  , 1.  ],
       [0.  , 0.  , 0.98, 1.  ],
       [0.  , 0.  , 0.  , 0.99]])

In [8]:
leximin_assignment_helper = leximin_assignment.LeximinAssignmentHelperV3(cost_matrix, capacities)
leximin_assignment_helper.solve()

/Users/quannguyen/anaconda3/envs/BayesFAI/lib/python3.7/site-packages/pulp/solvers.py:2080: UserWarning: GUROBI_CMD does provide good solution status of non optimal solutions
  warnings.warn('GUROBI_CMD does provide good solution status of non optimal solutions')


array([0, 1, 2, 3])

In [9]:
bottleneck_assignment_helper = bottleneck_assignment.BottleneckAssignmentHelperV2(cost_matrix, capacities)
bottleneck_assignment_helper.solve()

/Users/quannguyen/anaconda3/envs/BayesFAI/lib/python3.7/site-packages/pulp/solvers.py:2080: UserWarning: GUROBI_CMD does provide good solution status of non optimal solutions
  warnings.warn('GUROBI_CMD does provide good solution status of non optimal solutions')
/Users/quannguyen/anaconda3/envs/BayesFAI/lib/python3.7/site-packages/pulp/solvers.py:2080: UserWarning: GUROBI_CMD does provide good solution status of non optimal solutions
  warnings.warn('GUROBI_CMD does provide good solution status of non optimal solutions')


(array([0.98, 0.99]), array([2, 0, 1, 3]))

In [10]:
eff_assignment_helper = assignment.AssignmentHelperV2(cost_matrix, capacities)
eff_assignment_helper.ip_solve()

array([3, 0, 1, 2])

In [2]:
e = 1e-2

cost_matrix = np.array([
    [0, 1, 1, 1],
    [0, 1 - e, 1, 1],
    [0, 0, 1 - e, 1],
    [0, 0, 0, 1 - e]
])
capacities = [1, 1, 1, 1]

cost_matrix

array([[0.  , 1.  , 1.  , 1.  ],
       [0.  , 0.99, 1.  , 1.  ],
       [0.  , 0.  , 0.99, 1.  ],
       [0.  , 0.  , 0.  , 0.99]])

In [3]:
leximin_assignment_helper = leximin_assignment.LeximinAssignmentHelperV3(cost_matrix, capacities)
leximin_assignment_helper.solve(verbose=True)

Running from the beginning...
Number of agents assigned: 0 / 4
Current leximin: 1
Number of agents assigned: 1 / 4
Current leximin: 0.99
Reusing current leximin
Number of agents assigned: 2 / 4
Current leximin: 0.99
Reusing current leximin
Number of agents assigned: 3 / 4
Current leximin: 0.99


/Users/quannguyen/anaconda3/envs/BayesFAI/lib/python3.7/site-packages/pulp/solvers.py:2080: UserWarning: GUROBI_CMD does provide good solution status of non optimal solutions
  warnings.warn('GUROBI_CMD does provide good solution status of non optimal solutions')
/Users/quannguyen/anaconda3/envs/BayesFAI/lib/python3.7/site-packages/pulp/solvers.py:2080: UserWarning: GUROBI_CMD does provide good solution status of non optimal solutions
  warnings.warn('GUROBI_CMD does provide good solution status of non optimal solutions')


array([0, 1, 2, 3])

In [13]:
bottleneck_assignment_helper = bottleneck_assignment.BottleneckAssignmentHelperV2(cost_matrix, capacities)
bottleneck_assignment_helper.solve()

/Users/quannguyen/anaconda3/envs/BayesFAI/lib/python3.7/site-packages/pulp/solvers.py:2080: UserWarning: GUROBI_CMD does provide good solution status of non optimal solutions
  warnings.warn('GUROBI_CMD does provide good solution status of non optimal solutions')


(array([0.  , 0.99]), array([0, 1, 2, 3]))

In [14]:
eff_assignment_helper = assignment.AssignmentHelperV2(cost_matrix, capacities)
eff_assignment_helper.ip_solve()

array([3, 0, 1, 2])